### ISSUE TITLE
module not working

### ISSUE THREAD

**Issue by hafisabdulrasak** [OCA/hr-holidays#105]
## Module
Holidays natural period

## Describe the bug
module not working

## To Reproduce
16

1. create a time off request at the moment duration is correct 
2. after saving it, then the duration is changing to default odoo calculated value

**Comment by patrickkappertqubiq** [comment]
any news here?

**Comment by Evaguadaltech** [comment]
Buenas tardes, me he calcula bien las horas cuando es una jornada partida. Sin embargo, si es una jornada intensiva si calcula bien las horas. Te muestro la configuracion de las horas de trabajo asignadas al empleado:
![horario](https://github.com/user-attachments/assets/e5abfcc1-8864-429e-b485-225409ea21ae)
Las pruebas de ausencias que he realizado son las siguientes:
![ausencias](https://github.com/user-attachments/assets/fc3fd21a-0d37-4b3d-a96c-fb3b17cca2d0)

Gracias.
Un saludo.
