### ISSUE TITLE
hr_holidays_calendar_event_privacy: tests are failing in main 15.0 branch

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/hr-holidays#112]
## Module
hr_holidays_calendar_event_privacy

## Describe the bug
Tests are failing in the 15.0 branch, likely to a recent change in odoo's hr_holidays code.

## To Reproduce
**Affected versions**: 15.0 at least.

See all recent pipelines, for instance 15.0 branch last one: https://github.com/OCA/hr-holidays/actions/runs/7871142366/job/21473797702#step:8:40

**Expected behavior**
Tests pass

cc @grindtildeath as maintainer of the module, you may want to look into this one.

**Comment by JordiMForgeFlow** [comment]
Also referenced here: https://github.com/OCA/hr-holidays/pull/106

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Can you merge this one?
