### ISSUE TITLE
error from _leave_intervals

### ISSUE THREAD

**Issue by ho-ife** [OCA/hr-holidays#21]
Hello,

this happens with V13 Enterprise. Updated to latest code today.

When creating a new leaves reuquest this error shows up:

> ` Fehler:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/odoo13/odoo13-server/odoo/api.py", line 753, in get
>     value = self._data[field][record._ids[0]]
> KeyError: <NewId 0x7fdb56c702e8>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/odoo13/odoo13-server/odoo/fields.py", line 978, in __get__
>     value = env.cache.get(record, self)
>   File "/odoo13/odoo13-server/odoo/api.py", line 759, in get
>     raise CacheMiss(record, field)
> odoo.exceptions.CacheMiss: ('hr.leave(<NewId 0x7fdb56c702e8>,).number_of_hours_display', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/odoo13/odoo13-server/odoo/http.py", line 619, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/odoo13/odoo13-server/odoo/http.py", line 309, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/odoo13/odoo13-server/odoo/tools/pycompat.py", line 14, in reraise
>     raise value
>   File "/odoo13/odoo13-server/odoo/http.py", line 664, in dispatch
>     result = self._call_function(**self.params)
>   File "/odoo13/odoo13-server/odoo/http.py", line 345, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/service/model.py", line 93, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/http.py", line 338, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/odoo13/odoo13-server/odoo/http.py", line 909, in __call__
>     return self.method(*args, **kw)
>   File "/odoo13/odoo13-server/odoo/http.py", line 510, in response_wrap
>     response = f(*args, **kw)
>   File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1319, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/odoo13/odoo13-server/addons/web/controllers/main.py", line 1311, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/odoo13/odoo13-server/odoo/api.py", line 395, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/odoo13/odoo13-server/odoo/api.py", line 382, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/odoo13/odoo13-server/odoo/models.py", line 6032, in onchange
>     value = record[name]
>   File "/odoo13/odoo13-server/odoo/models.py", line 5579, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/odoo13/odoo13-server/odoo/fields.py", line 1002, in __get__
>     self.compute_value(recs)
>   File "/odoo13/odoo13-server/odoo/fields.py", line 1087, in compute_value
>     records._compute_field_value(self)
>   File "/odoo13/odoo13-server/odoo/models.py", line 3895, in _compute_field_value
>     getattr(self, field.compute)()
>   File "/odoo13/odoo13-server/addons/hr_holidays/models/hr_leave.py", line 437, in _compute_number_of_hours_display
>     number_of_hours = holiday._get_number_of_days(holiday.date_from, holiday.date_to, holiday.employee_id.id)['hours']
>   File "/odoo13/custom/addons/hr-holidays/hr_holidays_public/models/hr_leave.py", line 19, in _get_number_of_days
>     date_from, date_to, employee_id
>   File "/odoo13/odoo13-server/addons/hr_holidays/models/hr_leave.py", line 502, in _get_number_of_days
>     return employee._get_work_days_data(date_from, date_to)
>   File "/odoo13/odoo13-server/addons/resource/models/resource_mixin.py", line 78, in _get_work_days_data
>     intervals = calendar._work_intervals(from_datetime, to_datetime, resource, domain)
>   File "/odoo13/odoo13-server/addons/resource/models/resource.py", line 402, in _work_intervals
>     self._leave_intervals(start_dt, end_dt, resource, domain))
>   File "/odoo13/custom/addons/hr-holidays/hr_holidays_public/models/resource_calendar.py", line 67, in _leave_intervals
>     start_dt=start_dt, end_dt=end_dt, resource=resource, domain=domain, tz=tz
> TypeError: _leave_intervals() got an unexpected keyword argument 'tz' `

Expecting that 'tz' is related to timezone I checked timezone settings for user, employee and working hours. Everything is the same.

Saw this comment in the code for /hr_holidays_public/models/resource_calendar.py in Line 64:
`"""DEPRECATED since odoo/odoo#51542, but left as is for retro-compatibility"""
        # TODO: To be removed in v14 if not used in any place`

So I tried to comment the lines out and the module runs fine again.

Can you please check if this is maybe no longer needed and can be removed to run smoothly?

Kind regards

**Comment by pedrobaeza** [comment]
Is this reproducible on OCA runbot?
