### ISSUE TITLE
Public Holiday Leave Computation Not Working

### ISSUE THREAD

**Issue by aravinthu** [OCA/hr-holidays#28]
Public Holiday Defined
![image](https://user-images.githubusercontent.com/7602795/126486848-00f940b8-725f-4f23-b948-b86a43561add.png)

Leave Type Setting (Include Public Holiday)
![image](https://user-images.githubusercontent.com/7602795/126487880-b813e25c-3fdf-48b2-b7cd-d15120bb4632.png)

Settings are looks good, when i try to create leave it's included in leave Days. Works fine.

When i enable **Exclude Public Holiday** in Leave type settings, Public Holiday not skipped, still being calculated in **Leave Days**
![image](https://user-images.githubusercontent.com/7602795/126488489-0375472d-dd7d-4dcc-bb63-fc323d123ad8.png)

Total leave days not suppose to be **5 Days**, it should be **4 Days** bcoz we have defined 4th August as Holiday.

Please help to fix the issue.

**Comment by pedrobaeza** [comment]
You are not indicating the version. Please try to reproduce to problem in OCA runbot.

**Comment by aravinthu** [comment]
Sorry it's v13 and i have tested v12 also same problem,

http://3493090-13-0-56392f.runbot2.odoo-community.org/web#id=13&action=169&model=hr.leave&view_type=form&cids=&menu_id=117

check this record in runbot, 

Public holiday - 04/08/2021

Leave applied between 02/08/2021 -- 06/08/2021 using paid time off with exclude holiday option

Total leave suppose to be 4 days not 5 days

**Comment by pedrobaeza** [comment]
Mitchel Admin is not from Malaysia...

**Comment by aravinthu** [comment]
Ok Thanks, it's working v13, is there runbot available for this to test in v12

**Comment by pedrobaeza** [comment]
See the README. Closing as no issue.
