### ISSUE TITLE
Public Holidays not shown

### ISSUE THREAD

**Issue by pjdieulot** [OCA/hr-holidays#6]
Hi everyone, 

My name is Pierre and I am very new to Odoo (V13) world and GitHub community related to it. 

I am currently working on the Time Off app and I am very interested in your module, as I would like to display every public holidays in the calendar. 

However, I do not find the solution, even with the module installed. 

I suspect I have not correctly installed it and maybe you can help me there : 

I have downloaded the zip file and imported it in Odoo web. No error message or anything, but nothing new appeared in the Time Off module. 

Maybe I am missing a step here ? 

Thank you for your help. 

Pierre

**Comment by pedrobaeza** [comment]
Try to reproduce the error in runbot. See the button for it in the README file.

**Comment by pjdieulot** [comment]
Hi, 

Thank for your quick answer, however I am not sure what I am supposed to do once I've clicked on the runbot button ? This is what I get : 

![Capture d’écran 2020-04-09 à 8 54 21 AM](https://user-images.githubusercontent.com/63323036/78837497-f0d15380-7a3f-11ea-8ec9-468215c6af46.png)

I've seen in the readme file that normally, I should be able to set things directly from the Leaves module, but it seems I do not have the same paths than those described in the Readme. That is why I strongly think that the module is not installed correctly. 

This is how I proceed : 

Click on the Studio button 
![Capture d’écran 2020-04-09 à 9 00 44 AM](https://user-images.githubusercontent.com/63323036/78837881-bfa55300-7a40-11ea-9c64-3ac1c1fb912b.png)

"Personnalisation > Import" 
![Capture d’écran 2020-04-09 à 9 01 00 AM](https://user-images.githubusercontent.com/63323036/78837876-bf0cbc80-7a40-11ea-9e13-f295177dc0cb.png)

Load the file and then click on Import 
![Capture d’écran 2020-04-09 à 9 01 10 AM](https://user-images.githubusercontent.com/63323036/78837874-bd42f900-7a40-11ea-967b-a693032599a8.png)

Maybe it's not the correct way for this module ? 

Thanks for your help again.

**Comment by pedrobaeza** [comment]
https://runbot.odoo-community.org/runbot/290/13.0

**Comment by pjdieulot** [comment]
Thanks for the link. 

I managed to get access to the runbot but then again, I have entered some public holidays and I understand that they are excluded in the calculation of the days taken when on leaves, but they are not shown in the Calendar. This is the feature I would like to have on my platform.

**Comment by pedrobaeza** [comment]
Yes, exactly, that feature is not implemented.

See #2 that adds it.
