### ISSUE TITLE
[BUG][14.0][hr_holidays_public] action_validate() override doesn't loop self

### ISSUE THREAD

**Issue by dariodelzozzo** [OCA/hr-holidays#60]
## Module
hr_holidays_public version 14.0

## Describe the bug
The **hr_holidays_public** module, version 14.0 (don't know in other versions) has an override of the method `action_validate()` without a for loop for `self`.
Here:
[https://github.com/OCA/hr-holidays/blob/14.0/hr_holidays_public/models/hr_leave.py#L11](https://github.com/OCA/hr-holidays/blob/14.0/hr_holidays_public/models/hr_leave.py#L11)

This return an error when this actions.server (from standard module hr_holidays) is called on a recordset:
[https://github.com/odoo/odoo/blob/14.0/addons/hr_holidays/views/hr_leave_views.xml#L25](https://github.com/odoo/odoo/blob/14.0/addons/hr_holidays/views/hr_leave_views.xml#L25)

## To Reproduce
**Affected versions**: 14.0 (maybe 15.0 too because the method code is the same)

1. Install hr_holidays_public
2. Select more than one leave to approve in the tree
3. In the Actions menu select "HR Approval"
![image](https://user-images.githubusercontent.com/42646546/219106537-dcd68386-2f93-446c-ac97-9f36de077526.png)

4. An error is shown
![image](https://user-images.githubusercontent.com/42646546/219106854-ac5b2a37-6846-4801-9a76-a697f498a8a1.png)

**Expected behavior**
No errors in case of multiple records selected

**Additional context**
None

**Comment by pedrobaeza** [comment]
Can you please do the pull request for fixing this?

**Comment by dariodelzozzo** [comment]
> Can you please do the pull request for fixing this?

Done

**Comment by pedrobaeza** [comment]
Following on the PR.
